// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNBOcdXNHo9FjU7DnbIwlq7y2HSSy8l50',
    appId: '1:389971620598:web:4be335477365ee2a06b2d7',
    messagingSenderId: '389971620598',
    projectId: 'flutter-snake-game-4d18c',
    authDomain: 'flutter-snake-game-4d18c.firebaseapp.com',
    storageBucket: 'flutter-snake-game-4d18c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZDTDowFmLsyiUXmpQ1R5V0brlyRZtqU',
    appId: '1:389971620598:android:3a9aacd3047335e706b2d7',
    messagingSenderId: '389971620598',
    projectId: 'flutter-snake-game-4d18c',
    storageBucket: 'flutter-snake-game-4d18c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHQbkKVYfwjhtfnwunPJoSnEz4dIy1V0w',
    appId: '1:389971620598:ios:e5ade98897ca867f06b2d7',
    messagingSenderId: '389971620598',
    projectId: 'flutter-snake-game-4d18c',
    storageBucket: 'flutter-snake-game-4d18c.firebasestorage.app',
    iosBundleId: 'com.example.flutterSnakeGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNBOcdXNHo9FjU7DnbIwlq7y2HSSy8l50',
    appId: '1:389971620598:web:200d03afbbf66e4b06b2d7',
    messagingSenderId: '389971620598',
    projectId: 'flutter-snake-game-4d18c',
    authDomain: 'flutter-snake-game-4d18c.firebaseapp.com',
    storageBucket: 'flutter-snake-game-4d18c.firebasestorage.app',
  );
}
